In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from datetime import datetime
from zoneinfo import ZoneInfo

In [2]:
# Step 1: Load the Dataset
apps_df = pd.read_csv(r"C:\Users\DELL\Pictures\elevance_skills\play_store_data\apps.csv")
reviews_df = pd.read_csv(r"C:\Users\DELL\Pictures\elevance_skills\play_store_data\user_reviews.csv")

In [3]:
apps_df.head()

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [4]:
bar_data = apps_df.copy()

bar_data["Last Updated"] = pd.to_datetime(
    bar_data["Last Updated"],
    errors="coerce"
)

bar_data = bar_data.dropna(
    subset=["Last Updated"]
)

In [5]:
bar_data = bar_data[
    bar_data["Last Updated"].dt.month == 1
]

In [6]:
bar_data["Size"] = (
    bar_data["Size"]
    .astype(str)
    .str.replace("M", "", regex=False)
    .str.replace("k", "", regex=False)
    .str.strip()
)

bar_data["Size"] = pd.to_numeric(
    bar_data["Size"],
    errors="coerce"
)

In [7]:
bar_data = bar_data.dropna(
    subset=["Size"]
)

bar_data = bar_data[
    bar_data["Size"] < 10
]

In [8]:
bar_data["Rating"] = pd.to_numeric(
    bar_data["Rating"],
    errors="coerce"
)


bar_data["Reviews"] = pd.to_numeric(
    bar_data["Reviews"],
    errors="coerce"
)


bar_data["Installs"] = (
    bar_data["Installs"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.replace("+", "", regex=False)
)

bar_data["Installs"] = pd.to_numeric(
    bar_data["Installs"],
    errors="coerce"
)


bar_data = bar_data.dropna(
    subset=[
        "Rating",
        "Reviews",
        "Installs"
    ]
)

In [9]:
category_data = (
    bar_data
    .groupby("Category")
    .agg(
        Average_Rating=(
            "Rating",
            "mean"
        ),
        
        Total_Reviews=(
            "Reviews",
            "sum"
        ),
        
        Total_Installs=(
            "Installs",
            "sum"
        )
    )
    .reset_index()
)

In [10]:
category_data = category_data[
    category_data["Average_Rating"] >= 4.0
]

category_data

               Category  Average_Rating  Total_Reviews  Total_Installs
0        ART_AND_DESIGN        4.300000            132           10000
1   BOOKS_AND_REFERENCE        4.466667           2257          541000
3                COMICS        4.150000            187           15000
4         COMMUNICATION        4.100000         153852         7216100
6             EDUCATION        4.000000           2525          100000
7         ENTERTAINMENT        4.000000          11656         1000000
8                FAMILY        4.150000         389714        29827150
9               FINANCE        4.033333            498           58000
10                 GAME        4.000000         899273        28600000
13            LIFESTYLE        4.030000           9111          853600
15              MEDICAL        4.308333           7762          743600
16   NEWS_AND_MAGAZINES        4.400000           1019          111000
17            PARENTING        4.800000           7505          100000
18      PERSONALIZATION        4.269231         151515        13214500
19          PHOTOGRAPHY        4.350000          50509         1503200
20         PRODUCTIVITY        4.030000          83600         4170000
21             SHOPPING        4.700000             68           10000
22               SOCIAL        4.300000           1403          100000
23               SPORTS        4.400000          18180         1200000
24                TOOLS        4.105000         489390        40693000
25     TRAVEL_AND_LOCAL        4.250000            483           60000
27              WEATHER        4.000000           9307         1000000

In [11]:
top_categories = (
    category_data
    .sort_values(
        "Total_Installs",
        ascending=False
    )
    .head(10)
)

In [12]:
top_categories

           Category  Average_Rating  Total_Reviews  Total_Installs
24            TOOLS        4.105000         489390        40693000
8            FAMILY        4.150000         389714        29827150
10             GAME        4.000000         899273        28600000
18  PERSONALIZATION        4.269231         151515        13214500
4     COMMUNICATION        4.100000         153852         7216100
20     PRODUCTIVITY        4.030000          83600         4170000
19      PHOTOGRAPHY        4.350000          50509         1503200
23           SPORTS        4.400000          18180         1200000
27          WEATHER        4.000000           9307         1000000
7     ENTERTAINMENT        4.000000          11656         1000000

In [13]:
top_categories = top_categories.copy()

top_categories["Total_Reviews_Millions"] = (
    top_categories["Total_Reviews"]
    / 1000000
)


top_categories = top_categories.sort_values(
    "Total_Installs",
    ascending=False
)


top_categories

,Category,Average_Rating,Total_Reviews,Total_Installs,Total_Reviews_Millions
24,TOOLS,4.105000,489390,40693000,0.489390
8,FAMILY,4.150000,389714,29827150,0.389714
10,GAME,4.000000,899273,28600000,0.899273
18,PERSONALIZATION,4.269231,151515,13214500,0.151515
4,COMMUNICATION,4.100000,153852,7216100,0.153852
20,PRODUCTIVITY,4.030000,83600,4170000,0.083600
19,PHOTOGRAPHY,4.350000,50509,1503200,0.050509
23,SPORTS,4.400000,18180,1200000,0.018180
27,WEATHER,4.000000,9307,1000000,0.009307
7,ENTERTAINMENT,4.000000,11656,1000000,0.011656

In [14]:
# Get current time in IST

india_time = datetime.now(
    ZoneInfo("Asia/Kolkata")
)

current_hour = india_time.hour


# Show graph only between 3 PM and 5 PM IST

if 15 <= current_hour < 17:

    
    # Create positions for categories
    
    x = np.arange(
        len(top_categories)
    )
    
    
    # Width of bars
    
    width = 0.4
    
    
    # Create figure
    
    plt.figure(
        figsize=(14, 7)
    )
    
    
    # Average Rating bars
    
    plt.bar(
        x - width / 2,
        top_categories[
            "Average_Rating"
        ],
        width,
        label="Average Rating"
    )
    
    
    # Total Reviews bars
    
    plt.bar(
        x + width / 2,
        top_categories[
            "Total_Reviews_Millions"
        ],
        width,
        label="Total Reviews (Millions)"
    )
    
    
    # Category names
    
    plt.xticks(
        x,
        top_categories["Category"],
        rotation=45,
        ha="right"
    )
    
    
    # Title
    
    plt.title(
        "Average Rating and Total Reviews for Top 10 App Categories by Installs"
    )
    
    
    # X-axis
    
    plt.xlabel(
        "App Category"
    )
    
    
    # Y-axis
    
    plt.ylabel(
        "Value"
    )
    
    
    # Legend
    
    plt.legend()
    
    
    plt.tight_layout()
    
    
    # Display graph below Jupyter cell
    
    plt.show()


else:

    print(
        "This graph is available only between "
        "3 PM IST and 5 PM IST."
    )

This graph is available only between 3 PM IST and 5 PM IST.